In [1]:
import pandas as pd

In [2]:
#load data set
data = pd.read_excel('marketing_campaign.xlsx')

In [3]:
data.shape

(5000, 12)

In [4]:
data.describe()

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Securities Account,CD Account,Online,CreditCard,Offer_acceptance
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000
mean,45.338400,20.104600,73.774200,2.396400,1.937913,1.881000,56.498800,0.104400,0.06040,0.596800,0.294000,0.182200
std,11.463166,11.467954,46.033729,1.147663,1.747666,0.839869,101.713802,0.305809,0.23825,0.490589,0.455637,0.386048
min,23.000000,-3.000000,8.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
25%,35.000000,10.000000,39.000000,1.000000,0.700000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
50%,45.000000,20.000000,64.000000,2.000000,1.500000,2.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000
75%,55.000000,30.000000,98.000000,3.000000,2.500000,3.000000,101.000000,0.000000,0.00000,1.000000,1.000000,0.000000
max,67.000000,43.000000,224.000000,4.000000,10.000000,3.000000,635.000000,1.000000,1.00000,1.000000,1.000000,1.000000

In [5]:
#split the data set into input and output set
x=data.drop(["Offer_acceptance"],axis=1)
y=data["Offer_acceptance"]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
#sampling the the data set
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3)

In [8]:
from sklearn import tree

In [9]:
ctree=tree.DecisionTreeClassifier()

In [10]:
ctree=ctree.fit(x_train,y_train)

In [11]:
y_pred=ctree.predict(x_test)

In [12]:
print(y_pred)

[0 0 0 ... 0 0 0]

In [13]:
from sklearn import metrics

In [14]:
#default model
ctree = tree.DecisionTreeClassifier()
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
ctree_model = ctree.fit(x_train,y_train)
y_train_pred = ctree_model.predict(x_train)
print('train_accuracy:',metrics.accuracy_score(y_train,y_train_pred))
y_test_pred = ctree_model.predict(x_test)
print('test_accuracy:',metrics.accuracy_score(y_test,y_test_pred))

train_accuracy: 0.9997142857142857
test_accuracy: 0.8073333333333333

In [15]:
#comparing actual vs real
comparision_df = x_test.copy()
comparision_df['actual'] = y_test
comparision_df['Prediction'] = y_test_pred
comparision_df

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Securities Account,CD Account,Online,CreditCard,actual,Prediction
4064,63,39,50,1,0.000000,2,166,0,0,0,0,0,1
3980,46,22,89,4,1.400000,2,0,0,0,1,0,0,0
3871,40,16,125,2,1.900000,1,0,0,0,0,1,0,0
4724,34,8,21,4,1.000000,1,0,0,0,0,0,0,0
2970,54,30,121,2,1.100000,3,0,1,0,0,0,1,1
2235,63,37,141,2,6.900000,1,0,0,0,1,1,1,1
1651,62,36,158,2,6.300000,3,0,0,0,1,0,1,1
536,25,-1,43,3,2.400000,2,176,0,0,1,0,0,0
631,45,18,40,3,1.000000,2,0,0,0,1,0,0,0
4186,33,9,10,4,1.000000,1,81,0,0,0,1,0,1
3027,53,29,50,4,0.100000,3,152,0,0,1,0,0,0
2559,36,12,88,2,2.700000,1,0,0,0,1,0,0,0
4870,55,30,28,2,2.000000,2,0,0,0,1,1,0,1
2606,46,22,73,2,1.700000,1,216,0,0,1,0,0,0
3814,34,9,35,3,1.300000,1,0,0,0,0,0,0,0
3642,55,29,21,4,0.700000,3,0,1,0,1,0,0,0
2913,39,12,75,3,2.333333,2,0,0,0,1,1,0,0
1249,51,27,80,1,2.600000,2,0,0,0,1,1,1,1
815,62,38,35,1,1.900000,2,118,0,0,0,0,0,0
4548,58,33,73,4,0.700000,1,241,0,0,0,0,0,0
2433,37,11,123,1,2.300000,2,0,1,1,1,0,1,1
4974,59,33,64,4,1.700000,2,0,0,0,0,1,0,0
4777,32,8,30,4,0.400000,2,78,0,0,1,0,0,0
4723,39,15,125,1,3.500000,1,0,0,0,1,1,0,0
2604,37,10,35,4,1.000000,2,0,0,0,0,0,0,0
1270,43,18,60,2,2.200000,3,0,0,0,0,1,1,0
3161,28,4,88,1,5.400000,1,0,0,0,1,0,0,0
1368,46,21,40,4,1.900000,3,122,0,0,1,0,0,0
3272,35,9,85,2,1.800000,1,0,0,0,0,0,0,0
4865,50,24,133,4,1.400000,2,342,0,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2100,31,6,145,1,0.800000,1,84,0,0,1,0,0,0
4027,46,21,42,4,1.900000,3,0,0,0,1,0,0,0
2891,59,33,63,1,1.600000,1,0,0,0,1,1,0,0
1005,38,12,138,2,0.000000,1,0,1,0,1,0,0,0
4338,54,30,121,2,0.400000,1,0,0,0,1,0,0,0
1381,38,12,22,3,0.200000,2,0,0,0,1,0,0,0
2065,29,5,83,3,1.500000,1,0,0,0,1,1,0,0
2860,27,2,20,4,0.500000,3,0,0,0,1,0,0,0
342,43,19,118,2,3.300000,1,0,0,0,0,1,0,0
4255,59,35,78,2,2.800000,1,0,0,0,1,0,0,0
985,46,22,118,1,4.700000,1,159,0,0,0,1,0,0
30,59,35,35,1,1.200000,3,122,0,0,1,0,0,0
4576,55,30,41,2,0.600000,3,0,0,0,1,1,0,0
1216,50,25,84,1,1.300000,3,0,1,0,1,0,0,0
1812,43,19,128,1,4.700000,1,0,0,0,1,0,0,0
425,28,3,28,4,0.800000,1,0,0,0,1,0,0,1
2844,60,34,64,3,2.200000,3,0,0,0,0,0,0,0
926,33,9,22,4,0.400000,2,103,0,0,1,0,0,0
1396,42,18,43,1,0.300000,3,158,0,0,0,0,0,0
176,52,25,44,3,1.000000,2,135,0,0,1,0,0,0
4189,45,19,93,2,1.700000,2,0,0,0,0,0,0,0
712,41,16,10,2,0.300000,2,0,0,0,1,0,0,0
2732,33,9,38,1,2.100000,3,133,0,0,0,0,1,1
3421,49,23,125,1,2.400000,1,0,0,0,0,1,0,0
3299,60,34,90,4,1.900000,2,0,0,0,1,0,0,0
874,30,4,40,4,2.100000,3,0,0,0,1,1,1,0
282,34,9,71,4,0.700000,3,0,0,0,1,0,0,0
4567,46,20,19,3,0.500000,2,97,1,0,1,0,0,1
3043,47,22,42,3,2.700000,2,0,0,0,1,1,0,0
3036,33,9,14,4,0.700000,2,105,0,0,1,0,0,0

In [16]:
from sklearn.model_selection import cross_val_score

In [17]:
#cross_validation
cross_val_score(ctree,x,y,cv=5,scoring='accuracy')

array([0.79320679, 0.8       , 0.816     , 0.81      , 0.83983984])

In [18]:
cross_val_score(ctree,x,y,cv=5,scoring='accuracy').mean()

0.8120123256123257

In [19]:
#parameter tunning
from sklearn.model_selection import GridSearchCV

In [20]:
param_grid = { "criterion"       : ['gini', 'entropy'],
                "max_features"     : [4,5,6],
               "splitter"         : ['best', 'random'],
               "max_depth"        : [2,3],
               "min_samples_leaf" : [2,3]
             }

In [21]:
optimized_tree = GridSearchCV(ctree, param_grid, scoring = 'accuracy', cv=5)

In [22]:
optimized_tree.fit(x_train,y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'criterion': ['gini', 'entropy'], 'max_features': [4, 5, 6], 'splitter': ['best', 'random'], 'max_depth': [2, 3], 'min_samples_leaf': [2, 3]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [23]:
optimized_tree.best_score_

0.8888571428571429

In [24]:
optimized_tree.best_params_

{'criterion': 'entropy',
 'max_depth': 3,
 'max_features': 6,
 'min_samples_leaf': 3,
 'splitter': 'best'}

In [25]:
ctree_final = optimized_tree.best_estimator_

In [26]:
ctree_final

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=6, max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=3,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [27]:
y_pred = ctree_final.predict(x_test)
print('Accuracy', metrics.accuracy_score(y_pred, y_test))

Accuracy 0.8506666666666667

In [28]:
metrics.precision_score(y_pred,y_test)

0.29591836734693877

In [29]:
imp_df = pd.DataFrame()
imp_df['col_names']=x.columns
imp_df['Importance']= ctree_final.feature_importances_*100
imp_df.sort_values('Importance', ascending=False)
#imp_df

             col_names  Importance
2               Income   60.179747
5            Education   20.963386
3               Family   17.754758
0                  Age    1.102110
1           Experience    0.000000
4                CCAvg    0.000000
6             Mortgage    0.000000
7   Securities Account    0.000000
8           CD Account    0.000000
9               Online    0.000000
10          CreditCard    0.000000

In [30]:
#final model is saved
import pickle
pickle.dump(ctree_final, open('final_ctree_model_dec11.pk','wb'))

# refine the model by  changing the "accuracy" matrix to "recall" matrix
and increse the weight of desired class

In [31]:
param_grid = { "criterion"       : ['gini', 'entropy'],
                "max_features"     : [4,5,6],
               "splitter"         : ['best', 'random'],
               "max_depth"        : [2,3],
               "min_samples_leaf" : [2,3],
                "class_weight":[{0:1,1:2},{0:1,1:4}]
             }

In [32]:
optimized_tree = GridSearchCV(ctree, param_grid, scoring = 'recall', cv=5)

In [33]:
optimized_tree.fit(x_train,y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'criterion': ['gini', 'entropy'], 'max_features': [4, 5, 6], 'splitter': ['best', 'random'], 'max_depth': [2, 3], 'min_samples_leaf': [2, 3], 'class_weight': [{0: 1, 1: 2}, {0: 1, 1: 4}]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='recall', verbose=0)

In [34]:
optimized_tree.best_score_

0.6029591997302461

In [35]:
from sklearn.metrics import confusion_matrix

In [36]:
print(confusion_matrix(y_test,y_pred))

[[1189   17]
 [ 207   87]]

In [37]:
metrics.recall_score(y_test,y_pred)

0.29591836734693877

In [38]:
optimized_tree.best_params_

{'class_weight': {0: 1, 1: 4},
 'criterion': 'gini',
 'max_depth': 2,
 'max_features': 5,
 'min_samples_leaf': 2,
 'splitter': 'best'}

In [39]:
ctree_final1 = optimized_tree.best_estimator_
ctree_final1

DecisionTreeClassifier(class_weight={0: 1, 1: 4}, criterion='gini',
            max_depth=2, max_features=5, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=2, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [40]:
y_pred = ctree_final1.predict(x_test)
print('Accuracy', metrics.accuracy_score(y_pred, y_test))

Accuracy 0.774

In [41]:
#new refine model  model is saved
import pickle
pickle.dump(ctree_final1, open('final_ctree_model1_dec11.pk','wb'))